/**
 * Evidence-bound paper figures, rendered as plain TikZ text artifacts.
 *
 * Same contract as the generated tables: derived ONLY from the committed
 * machine-readable reports, written to paper/generated/, never hand-edited —
 * `make check` fails on any byte drift. TikZ (not pgfplots, not binary PDFs)
 * keeps the artifacts text-diffable and compiles with the core TeX install.
 *
 * Caption language matches the manuscript's register: these are descriptive
 * empirical rank diagnostics, not calibration guarantees.
 */
import { readFileSync } from "fs";
import { join } from "path";

type CalRow = { level: number; observed: number; expected_null: number };

const DETECTOR_ORDER = ["conv_ae", "iforest", "pca", "spectral_residual", "trace_c"] as const;
const DETECTOR_LABEL: Record<string, string> = {
  conv_ae: "conv-AE",
  iforest: "IForest",
  pca: "PCA",
  spectral_residual: "SR",
  trace_c: "TRACE-C",
};

export type CalibrationFigureData = {
  detector: string;
  y2019: CalRow[];
  y2020pre: CalRow[];
}[];

export function loadCalibrationFigureData(root: string): CalibrationFigureData {
  const report = JSON.parse(
    readFileSync(join(root, "data/reports/baselines-report.json"), "utf8")
  ) as {
    baselines: {
      detector: string;
      y2019: { calibration: CalRow[] };
      y2020: { calibration_precovid?: CalRow[] };
    }[];
    trace_c: {
      y2019: { calibration: CalRow[] };
      y2020: { calibration_precovid?: CalRow[] };
    };
  };
  const rows = [
    ...report.baselines.map((b) => ({
      detector: b.detector,
      y2019: b.y2019.calibration,
      y2020pre: b.y2020.calibration_precovid ?? [],
    })),
    {
      detector: "trace_c",
      y2019: report.trace_c.y2019.calibration,
      y2020pre: report.trace_c.y2020.calibration_precovid ?? [],
    },
  ];
  rows.sort(
    (a, b) =>
      DETECTOR_ORDER.indexOf(a.detector as (typeof DETECTOR_ORDER)[number]) -
      DETECTOR_ORDER.indexOf(b.detector as (typeof DETECTOR_ORDER)[number])
  );
  return rows;
}

const ratio = (r: CalRow) => r.observed / r.expected_null;

export function renderCalibrationFigure(data: CalibrationFigureData): string {
  // Geometry (cm). One panel per segment; per detector a pair of bars
  // (thresholds .05 and .01); dashed reference at observed = alpha*n.
  const BAR = 0.42;
  const PAIR_GAP = 0.1;
  const GROUP_GAP = 0.5;
  const Y_UNIT = 1.35; // cm per ratio unit
  const Y_MAX = 2.3;
  const groupPitch = 2 * BAR + PAIR_GAP + GROUP_GAP;
  const panelWidth = data.length * groupPitch - GROUP_GAP;

  const panel = (title: string, pick: (d: CalibrationFigureData[number]) => CalRow[]) => {
    const lines: string[] = [];
    lines.push(`% panel: ${title}`);
    lines.push(
      `\\draw[->] (0,0) -- (0,${(Y_MAX * Y_UNIT).toFixed(3)});`,
      `\\draw (0,0) -- (${panelWidth.toFixed(3)},0);`
    );
    for (const yt of [0.5, 1.0, 1.5, 2.0]) {
      const y = (yt * Y_UNIT).toFixed(3);
      lines.push(
        `\\draw (0,${y}) -- (-0.07,${y}) node[left,font=\\tiny] {${yt.toFixed(1)}};`
      );
    }
    lines.push(
      `\\draw[dashed,gray] (0,${Y_UNIT.toFixed(3)}) -- (${panelWidth.toFixed(3)},${Y_UNIT.toFixed(3)});`
    );
    data.forEach((d, gi) => {
      const rows = pick(d);
      const x0 = gi * groupPitch;
      rows.forEach((r, bi) => {
        const x = x0 + bi * (BAR + PAIR_GAP);
        const h = Math.min(ratio(r), Y_MAX) * Y_UNIT;
        const fill = bi === 0 ? "black!55" : "black!22";
        lines.push(
          `\\fill[${fill}] (${x.toFixed(3)},0) rectangle (${(x + BAR).toFixed(3)},${h.toFixed(3)});`,
          `\\node[above,font=\\tiny] at (${(x + BAR / 2).toFixed(3)},${h.toFixed(3)}) {${ratio(r).toFixed(2)}};`
        );
      });
      lines.push(
        `\\node[below,font=\\tiny] at (${(x0 + BAR + PAIR_GAP / 2).toFixed(3)},-0.06) {${DETECTOR_LABEL[d.detector] ?? d.detector}};`
      );
    });
    lines.push(
      `\\node[above,font=\\small] at (${(panelWidth / 2).toFixed(3)},${(Y_MAX * Y_UNIT).toFixed(3)}) {${title}};`
    );
    return lines.join("\n");
  };

  return `% GENERATED by scripts/generate-paper-figures.ts from
% data/reports/baselines-report.json — do not edit by hand.
\\begin{figure*}[t]
\\centering
\\begin{tikzpicture}
${panel("2019 test (Jul--Dec)", (d) => d.y2019)}
\\begin{scope}[xshift=${(panelWidth + 1.4).toFixed(3)}cm]
${panel("2020 pre-COVID (frozen segment)", (d) => d.y2020pre)}
\\end{scope}
\\node[font=\\tiny,anchor=west] at (0,-0.55)
  {dark bars: $p\\leq.05$; light bars: $p\\leq.01$; dashed line: observed $=\\alpha n$};
\\end{tikzpicture}
\\caption{Empirical rank diagnostics under the shared scoring envelope:
observed counts of outer rank values at thresholds $.05$ and $.01$, expressed
as a ratio to the arithmetic benchmark $\\alpha n$ (dashed line). Values are
read directly from the committed reports. Descriptive only: autocorrelation,
drift, reused references, and known events preclude reading these as uniform
$p$-value or false-discovery guarantees (Section~\\ref{sec:results}).}
\\label{fig:rank-diagnostics}
\\end{figure*}
`;
}

export type HoldoutTimelineData = {
  points: { i: number; S: number }[];
  monthTicks: { i: number; label: string }[];
  events: { id: string; label: string; from: number; to: number }[];
  maxS: number;
  nWindows: number;
};

const EVENT_LABEL: Record<string, string> = {
  "STORM-CIARA-2020-02-09": "Ciara",
  "STORM-DENNIS-2020-02-15": "Dennis",
  "COVID-LOCKDOWN-2020-03-23": "COVID onset",
};

export function loadHoldoutTimelineData(root: string): HoldoutTimelineData {
  const report = JSON.parse(
    readFileSync(join(root, "data/reports/trace-c-holdout-report.json"), "utf8")
  ) as { timeline: { w: number; date: string; S: number; known: string | null }[] };
  const tl = report.timeline;
  const points = tl.map((x, i) => ({ i, S: x.S }));
  const monthTicks: { i: number; label: string }[] = [];
  let lastMonth = "";
  const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  tl.forEach((x, i) => {
    const m = x.date.slice(0, 7);
    if (m !== lastMonth) {
      lastMonth = m;
      monthTicks.push({ i, label: MONTHS[Number(x.date.slice(5, 7)) - 1]! });
    }
  });
  const events: HoldoutTimelineData["events"] = [];
  for (const [id, label] of Object.entries(EVENT_LABEL)) {
    const idx = tl.map((x, i) => (x.known === id ? i : -1)).filter((i) => i >= 0);
    if (idx.length) events.push({ id, label, from: idx[0]!, to: idx[idx.length - 1]! });
  }
  events.sort((a, b) => a.from - b.from);
  return {
    points,
    monthTicks,
    events,
    maxS: Math.max(...points.map((p) => p.S)),
    nWindows: tl.length,
  };
}

export function renderHoldoutTimelineFigure(data: HoldoutTimelineData): string {
  const WIDTH = 16.2; // cm
  const HEIGHT = 3.0; // cm
  const px = (i: number) => (i / Math.max(data.nWindows - 1, 1)) * WIDTH;
  const py = (S: number) => (Math.max(S, 0) / data.maxS) * HEIGHT;

  const bands = data.events
    .map((e, idx) => {
      const a = px(e.from).toFixed(3);
      const b = px(Math.max(e.to, e.from + 4)).toFixed(3);
      // Alternate label heights so adjacent bands (Ciara/Dennis, one week
      // apart) do not collide.
      const labelY = (HEIGHT + 0.05 + 0.3 * (idx % 2)).toFixed(3);
      return (
        `\\fill[black!12] (${a},0) rectangle (${b},${HEIGHT.toFixed(3)});\n` +
        `\\node[above,font=\\tiny] at (${((px(e.from) + px(e.to)) / 2).toFixed(3)},${labelY}) {${e.label}};`
      );
    })
    .join("\n");

  // Chunked polyline: one TikZ path per 400 points keeps TeX memory flat.
  const chunks: string[] = [];
  for (let start = 0; start < data.points.length; start += 400) {
    const seg = data.points.slice(Math.max(start - 1, 0), start + 400);
    const coords = seg.map((p) => `(${px(p.i).toFixed(3)},${py(p.S).toFixed(3)})`).join(" ");
    chunks.push(`\\draw[black!70,line width=0.25pt] plot coordinates {${coords}};`);
  }

  const ticks = data.monthTicks
    .map(
      (t) =>
        `\\draw (${px(t.i).toFixed(3)},0) -- (${px(t.i).toFixed(3)},-0.08) node[below,font=\\tiny] {${t.label}};`
    )
    .join("\n");

  return `% GENERATED by scripts/generate-paper-figures.ts from
% data/reports/trace-c-holdout-report.json — do not edit by hand.
\\begin{figure*}[t]
\\centering
\\begin{tikzpicture}
${bands}
${chunks.join("\n")}
${ticks}
\\draw (0,0) -- (${WIDTH.toFixed(3)},0);
\\node[left,font=\\tiny] at (0,${HEIGHT.toFixed(3)}) {S=${data.maxS.toFixed(1)}};
\\node[left,font=\\tiny] at (0,0) {S=0};
\\end{tikzpicture}
\\caption{Frozen 2020 segment: aggregate score $S$ for each of the
${"$" + data.nWindows + "$"} two-hour windows, scored with strictly-prior
references under the configuration committed before 2020 data was examined.
Shaded bands mark the post-hoc event annotations (Storms Ciara and Dennis;
the COVID-19 lockdown onset). The record rule selected no 2020 window
(Section~\\ref{sec:results}); event windows rank in the upper tail without
crossing the record threshold.}
\\label{fig:holdout-timeline}
\\end{figure*}
`;
}
